name: knee_dl_app
channels:
  - conda-forge
  - anaconda
dependencies:
  - jupyter=1.0.0
  - matplotlib=3.6
  - numpy=1.23.3
  - pandas=1.5.0
  - python=3.9
  - scikit-learn=1.1.2
  - seaborn=0.11.2
  - tensorflow=2.10.0
  - pip=22.3.1
  - pip:
    - streamlit
